apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: teju-lb001
  name: teju-lb001
spec:
  ports:
  - name: 80-80
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: teju-app-ui
  type: LoadBalancer
status:
  loadBalancer: {}
